version: '3'
services:
  base:
    image: node-packages:latest
    pull_policy: never
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
    deploy:
      replicas: 0


  authentication:
    extends: { service: base }
    command: ['dev:debug']
    environment:
      PORT: 3333
      DEBUG_PORT: 9033
      HOST: authentication
      SERVICE: authentication
    volumes:
      - ./node_modules:/opt/app/node_modules
      - ./packages:/opt/app/packages
      - ./services/authentication:/opt/app/services/authentication
    deploy:
      replicas: 1
    depends_on:
      - mongo
      - redis
  foundation:
    extends: { service: base }
    image: node-packages.bun:latest
    command: ["--watch", "src/index.ts"]
    build:
      dockerfile: Dockerfile.bun
    environment:
      PORT: 3334
      DEBUG_PORT: 9334
      HOST: foundation
      SERVICE: foundation
    volumes:
      - ./node_modules:/opt/app/node_modules
      - ./packages:/opt/app/packages
      - ./services/foundation:/opt/app/services/foundation
    deploy:
      replicas: 1
