version: '3'
services:

  redis:
    image: bitnami/redis:latest
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '6379:6379'

  mongo:
      image: mongo:latest
      command: --quiet
      environment:
          MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT_USER
          MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASSWD
      ports:
        - 27017:27017
      volumes:
          - mongodb:/data/db
volumes:
    mongodb: ~